export const AI_MODELS = [
  // ── Google Gemini ────────────────────────────
  {
    id: 'gemini-2.0-flash',
    label: 'Gemini 2.0 Flash',
    provider: 'Google',
    free: true,
    fast: true,
    description: 'Latest Gemini — fast and free',
    badge: 'FREE',
    badgeColor: '#4ade80',
  },

  // ── Groq ─────────────────────────────────────
  {
    id: 'llama-3.3-70b-versatile',
    label: 'Llama 3.3 70B',
    provider: 'Groq',
    free: true,
    fast: true,
    description: '1,000 req/day free — very capable',
    badge: 'FREE',
    badgeColor: '#4ade80',
  },
  {
    id: 'llama-3.1-8b-instant',
    label: 'Llama 3.1 8B',
    provider: 'Groq',
    free: true,
    fast: true,
    description: '14,400 req/day free — ultrafast',
    badge: 'FREE',
    badgeColor: '#4ade80',
  },
  {
    id: 'mixtral-8x7b-32768',
    label: 'Mixtral 8x7B',
    provider: 'Groq',
    free: true,
    fast: true,
    description: '14,400 req/day — powerful & free',
    badge: 'FREE',
    badgeColor: '#4ade80',
  },
  {
    id: 'gemma2-9b-it',
    label: 'Gemma 2 9B',
    provider: 'Groq',
    free: true,
    fast: true,
    description: '14,400 req/day — Google open model',
    badge: 'FREE',
    badgeColor: '#4ade80',
  },

  // ── OpenRouter ───────────────────────────────
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    label: 'Llama 3.1 8B (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: true,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    label: 'Llama 3.3 70B (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: false,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'google/gemma-2-9b-it',
    label: 'Gemma 2 9B (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: true,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'mistralai/mistral-7b-instruct',
    label: 'Mistral 7B (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: true,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'deepseek/deepseek-r1',
    label: 'DeepSeek R1 (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: false,
    description: 'Free via OpenRouter — best reasoning',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'deepseek/deepseek-chat',
    label: 'DeepSeek V3 (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: true,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    label: 'Qwen 2.5 72B (OpenRouter)',
    provider: 'OpenRouter',
    free: true,
    fast: false,
    description: 'Free via OpenRouter',
    badge: 'FREE',
    badgeColor: '#f97316',
  },

  // ── GitHub Models (FREE — no commercial use) ──
  {
    id: 'gpt-4o',
    label: 'GPT-4o (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: true,
    description: '150 req/day — no commercial use',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'gpt-4o-mini',
    label: 'GPT-4o Mini (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: true,
    description: '150 req/day — no commercial use',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'Meta-Llama-3.1-405B-Instruct',
    label: 'Llama 3.1 405B (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: false,
    description: '150 req/day — most powerful free',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'Meta-Llama-3.3-70B-Instruct',
    label: 'Llama 3.3 70B (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: true,
    description: '150 req/day — no commercial use',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'DeepSeek-R1',
    label: 'DeepSeek R1 (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: false,
    description: '150 req/day — best reasoning free',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'Phi-4',
    label: 'Phi-4 (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: true,
    description: '150 req/day — Microsoft model',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },
  {
    id: 'Mistral-Large-2411',
    label: 'Mistral Large (GitHub)',
    provider: 'GitHub',
    free: true,
    fast: true,
    description: '150 req/day — no commercial use',
    badge: 'FREE',
    badgeColor: '#22c55e',
  },

  // ── OpenAI ───────────────────────────────────
  {
    id: 'gpt-3.5-turbo',
    label: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    free: false,
    fast: true,
    description: 'Requires OpenAI API key',
    badge: 'API KEY',
    badgeColor: '#f59e0b',
  },
  {
    id: 'gpt-4o',
    label: 'GPT-4o',
    provider: 'OpenAI',
    free: false,
    fast: false,
    description: 'Most capable — paid OpenAI key',
    badge: 'PAID',
    badgeColor: '#f87171',
  },

  // ── Together AI ──────────────────────────────
  {
    id: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    label: 'Mixtral (Together)',
    provider: 'Together AI',
    free: false,
    fast: true,
    description: 'Requires Together AI key',
    badge: 'API KEY',
    badgeColor: '#a78bfa',
  },
]

export const DEFAULT_MODEL = 'gemini-2.0-flash'
export const FREE_MODELS = AI_MODELS.filter((m) => m.free)

export function getModelById(id) {
  return AI_MODELS.find((m) => m.id === id) || AI_MODELS[0]
}